- name: clone dotfiles
  git:
    repo: git@github.com:dnlznk/.dotfiles.git
    dest: "{{ lookup('env', 'HOME' )}}/.dotfiles"
    recursive: true
    update: true
    accept_hostkey: true
    key_file: "{{ dest_key }}"
    force: true
    version: main
  tags:
    - install
    - dotfiles

- name: remove existing zshenv
  shell: "rm {{ lookup('env', 'HOME') }}/.zshenv"
  ignore_errors: true
  tags: 
    - install
    - dotfiles

- name: stow dotfiles
  shell: cd $HOME/.dotfiles && ./linux
  tags:
    - install
    - dotfiles
