- name: check if neovim is installed
  shell: command -v nvim
  register: neovim_exists
  ignore_errors: true
  tags: 
    - install
    - neovim

- name: clone neovim repo
  when: neovim_exists is failed
  git:
    repo: https://github.com/neovim/neovim
    dest: "{{ lookup('env', 'HOME') }}/.neovim"
  tags:
    - install
    - neovim

- name: build neovim
  when: neovim_exists is failed
  shell: "cd {{ lookup('env', 'HOME') }}/.neovim && git checkout tags/v0.9.1 && make CMAKE_BUILD_TYPE=Release"
  tags:
    - install
    - neovim

- name: install neovim
  when: neovim_exists is failed
  shell: "cd {{ lookup('env', 'HOME') }}/.neovim && make install"
  tags:
    - install
    - neovim

- name: install python neovim plugin
  when: neovim_exists is failed
  shell: python3 -m pip install neovim

- name: install packages needed for neovim
  dnf: name={{ item }}
  with_items:
    - ripgrep
    - fd-find
    - g++
  tags:
    - install
    - neovim
