- name: check nvm is installed
  shell: command -v nvm
  register: nvim_exists
  ignore_errors: true
  tags:
    - install
    - node

- name: install node version manager
  when: nvim_exists is failed
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
  tags:
    - install
    - node

- name: install node lts
  shell: "source {{ lookup('env', 'HOME') }}/.bashrc && nvm install --lts"
  ignore_errors: true
  tags: 
    - install
    - node

- name: install node neovim plugins
  shell: "source {{ lookup('env', 'HOME') }}/.bashrc && npm i -g neovim tree-sitter-cli prettier @johnnymorganz/stylua-bin tsc"
  ignore_errors: true
  tags:
    - install
    - node
