- name: check nvm is installed
  shell: command -v nvm
  register: nvim_exists
  ignore_errors: true
  tags:
    - install
    - node

- name: download node version manager
  when: nvim_exists is failed
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/v0.39.3/install.sh
    dest: /tmp/nvm-install.sh
    mode: '0755'
    force: yes
  ignore_errors: true
  tags:
    - install
    - node

- name: install node version manager
  when: nvim_exists is failed
  shell: /tmp/nvm-install.sh
  tags:
    - install
    - node

- name: install node lts
  shell: "source {{ lookup('env', 'HOME') }}/.bashrc && nvm install --lts"
  ignore_errors: true
  tags: 
    - install
    - node

- name: install node neovim plugins
  shell: "source {{ lookup('env', 'HOME') }}/.bashrc && npm i -g neovim tree-sitter-cli prettier @johnnymorganz/stylua-bin tsc"
  ignore_errors: true
  tags:
    - install
    - node
