- name: check if ssh was initialized
  shell: "find {{ dest_key }}"
  register: ssh_initialized
  ignore_errors: true
  tags: 
    - install
    - ssh
    - dotfiles

- name: ensure .ssh exists
  when: ssh_initialized is failed
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
    owner: "{{ env.USER }}"
    group: "{{ env.USER }}"
  tags:
    - install
    - ssh
    - dotfiles

- name: copy config
  when: ssh_initialized is failed
  copy: 
    src: "{{ source_config }}"
    dest: "{{ dest_config }}"
    owner: "{{ env.USER }}"
    group: "{{ env.USER }}"
    mode: 0644
  tags: 
    - install
    - ssh
    - dotfiles

- name: copy public ssh key
  when: ssh_initialized is failed
  copy: 
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    owner: "{{ env.USER }}"
    group: "{{ env.USER }}"
    mode: 0644
  tags: 
    - install
    - ssh
    - dotfiles

- name: copy ssh key
  when: ssh_initialized is failed
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    owner: "{{ env.USER }}"
    group: "{{ env.USER }}"
    mode: 0600
  tags: 
    - install
    - ssh
    - dotfiles

- name: set authorized from file
  when: ssh_initialized is failed
  authorized_key:
    # user: "{{ lookup('env', 'USER') }}"
    user: root
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/github.pub') }}"
  tags:
    - install
    - ssh
    - dotfiles
