- name: install system packages
  dnf:
    name: '{{ item }}'
  with_items:
    - curl
    - make
    - cmake
    - util-linux-user
    - which
    - ninja-build
    - gcc
    - unzip
    - gettext
    - python3-pip
    - dnf-plugins-core
    - wget
    - tmux
    - fzf
    - xclip
    - tldr
    - gnome-tweaks
    - stow
    - alacritty
    - i3
    - ripgrep
    - fd-find
    - g++
  tags:
    - install
    - system

- name: add rpm fusion packages
  shell: dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
  tags:
    - install
    - system

- name: install appstream metadata
  shell: dnf groupupdate -y core
  tags:
    - install
    - system

- name: set gnome default terminal
  shell: gsettings set org.gnome.desktop.default-applications.terminal exec alacritty && gsettings set org.gnome.desktop.default-applications.terminal exec-arg '-e'
  tags:
    - install
    - system

- name: add flatpak repository
  shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  tags:
    - install
    - system

- name: install spotify
  shell: flatpak install -y com.spotify.Client
  tags: 
    - install
    - system

- name: install nvidia driver
  shell: dnf install akmod-nvidia
  tags:
    - install
    - system
