- name: check zsh is installed
  shell: command -v zsh
  register: zsh_exists
  ignore_errors: true
  tags: 
    - install
    - zsh

- name: install zsh
  when: zsh_exists is failed
  become_user: root
  dnf:
    name: zsh
  tags:
    - install
    - zsh

- name: change shell
  when: zsh_exists is failed
  become_user: root
  shell: "chsh -s $(which zsh) {{ user }}"
  tags:
    - install
    - zsh
